recipe_platform/recipe_platform/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipe_platform/recipes/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('regiter/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.register, name='logout'),

    path('recipes/', views.recipe_list, name='recipes'),
    path('recipes/create/', views.create_recipie, name='create_recipe'),
    path('recipes/<id:recipe_id>/', views.recipe_detail, name='recipe_detail'),
]

recipe_platform/recipes/models.py
from django.db import models
from django.contrib.auth import User

# Create your models here.

# This is a Django model that will be used to create a 
# database table to store recipe data.
class Recipe(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    ingredients = models.TextField()
    instruction = models.TextField()
    cooking_time = models.IntegerField(help_text="Time in min")

    difficulty = models.CharField(max_length=50, choices=[
        ('Easy', 'Easy'),
        ('Medium', 'Medium'),
        ('Hard', 'Hard')
    ])

    food_type = models.CharField(max_length=50, choices=[
        ('Vegetarian', 'Vegetarian'),
        ('Non-Vegetarian', 'Non-Vegetarian'),
        ('Vegan', 'Vegan')
    ], default='Vegetarian')  # Default value set to 'Vegetarian'

    image= models.ImageField(upload_to='recipes/')

    # Add a foreign key for recipe author from the 'User'
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    #  This method defines how a Recipe object is represented as a string.
    #  In this case, whenever a Recipe instance is printed or displayed (e.g., in the Django admin),
    #  it will show the title of the recipe.
    def __str__(self):
        return self.title

recipe_platform/recipes/forms.py
from django import forms
from django.contrib.auth import User
from django.contrib.auth.forms import UserCreationForm

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        feilds = ['username', 'email', 'password1', 'password2']


from .models import Recipe
class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['title', 'description',
                'ingredients', 'instructions', 'cooking_time', 
                'difficulty', 'image']

recipe_platform/recipes/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
from .forms import RegisterForm


from django.contrib.auth.decorators import login_required
from .models import Recipe
from .forms import RecipeForm


# Create your views here.

def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('login')
    else:
        form = RegisterForm()
    return render(request, 'register.html', {'form': form})        

def user_login(request):
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid:
            user = form.get_user()
            login(request, user)
            return redirect('home')
    else:
        form = AuthenticationForm()
    return render(request, 'login.html', {'form': form}) 


def user_logout(request):
    logout(request)
    return redirect('login')

# ----------------------------------------------------
# Before rendering login is required
@login_required # decorator
def create_recipie(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid:
            recipe = form.save(commit = False)
            recipe.author = request.user
            recipe.save()
            return redirect('recipe_list')
    else:
        form = RecipeForm()
    return render(request, 'create_recipe.html', {'form' : form}) 

@login_required
def recipe_list(request):
    recipes = Recipe.objects.all()
    return render(request, 'recipe_list.html', {'recipies' : recipes})

@login_required
def recipe_detail(request, recipe_id):
    recipe = Recipe.objects.get(id=recipe_id)
    return render(request, 'recipe_detail.html', {'recipie' : recipe})

recipe_platform/recipes/templates/recipes/create_recipe.html
<h2>Create Recipe</h2>
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>

recipe_platform/recipes/templates/recipes/login.html
<h2>Login</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
</form>

recipe_platform/recipes/templates/recipes/recipe_detail.html
<h2>{{ recipe.title }}</h2>
<img src="{{ recipe.image.url }}" alt="Recipe Image">
<p>{{ recipe.description }}</p>
<p>Ingredients: {{ recipe.ingredients }}</p>
<p>Instructions: {{ recipe.instructions }}</p>
<p>Cooking Time: {{ recipe.cooking_time }} minutes</p>
<p>Difficulty: {{ recipe.get_difficulty_display }}</p>

recipe_platform/recipes/templates/recipes/recipe_list.html
<h2>Recipes</h2>
<ul>
    {% for recipe in recipes %}
        <li>
            <a href="{% url 'recipe_detail' recipe.id %}">{{ recipe.title }}</a>
        </li>
    {% endfor %}
</ul>

recipe_platform/recipes/templates/recipes/register.html
<h2>Register</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Register</button>
</form>